# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ] 
    paths:
    - "*"

jobs: 
  build:

    runs-on: self-hosted
    environment: SIT
    env: 
      varSIT: "test"
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
       # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Display dotnet version 
      run: dotnet --version
    - name: env var
      run: |
        echo "local jobs variable $env:varSIT"
        echo "repository variable : ${{ vars.OILVERSION }}"
    - name: PS script ProgramFiles
      run: |
           ping 198.18.100.6
#           ${env:ProgramFiles(x86)}
    - name: Deploy via PS
      run: |
        .\ConsoleAppNew\ConsoleApp1\DeployScript.ps1
    - name: PS script whoami
      run: |
        whoami
        echo $env:GITHUB_WORKSPACE
